-- CLIENT FRESH INSTALL
-- ONLY for a brand-new empty Supabase project.
-- Run once in SQL Editor. Do not run on an existing live client database.
-- Generated from the reviewed base install + current migrations.



-- ============================================================
-- BEGIN supabase/review-install.sql
-- ============================================================

-- Kino site review migration. Back up the database first. All changes are atomic.
begin;

-- setup.sql
-- Run once in Supabase SQL Editor. No existing film/order/user rows are deleted.
-- Back up the database first. This intentionally closes direct browser REST access.
create table if not exists public.users (
 id bigint generated by default as identity primary key, phone text unique not null,
 pin text not null, user_id text unique not null, failed_attempts integer default 0,
 locked_until timestamptz, created_at timestamptz not null default now()
);
-- Existing 4-character PIN columns must accommodate scrypt hashes.
alter table public.users alter column pin type text;
alter table public.users add column if not exists failed_attempts integer default 0;
alter table public.users add column if not exists locked_until timestamptz;
alter table public.users add column if not exists created_at timestamptz not null default now();
create unique index if not exists kino_users_phone_unique on public.users(phone);
create table if not exists public.films (
 id bigint generated by default as identity primary key, title text not null,
 views integer default 0, op integer default 0, price integer default 0,
 badge text default 'Хэлтэй', free boolean default false, locked boolean default true,
 url text default '', img text default '', bg text default '#1a0820',
 preview_url text default '', created_at timestamptz not null default now()
);
alter table public.films add column if not exists preview_url text default '';
alter table public.films add column if not exists description text not null default '';
-- Copy only already-designated trailers into their public column.
update public.films set preview_url=split_part(url,'|||',2)
 where coalesce(preview_url,'')='' and position('|||' in coalesce(url,''))>0;
create table if not exists public.pending_payments (
 id bigint generated by default as identity primary key, ref_code text not null,
 user_id bigint, film_id bigint, phone text, plan text not null default 'single',
 amount numeric not null, status text not null default 'pending',
 confirmed_at timestamptz, created_at timestamptz not null default now()
);
alter table public.pending_payments alter column film_id drop not null;
alter table public.pending_payments add column if not exists confirmed_at timestamptz;
alter table public.pending_payments add column if not exists phone text;
-- If duplicate refs exist, this fails and rolls back; inspect them manually, do not delete blindly.
create unique index if not exists kino_payment_ref_unique on public.pending_payments(ref_code);
create table if not exists public.contact_messages (
 id bigint generated by default as identity primary key, phone text, message text,
 reply text, read boolean default false, is_announcement boolean default false,
 announcement_image text, created_at timestamptz not null default now()
);
create table if not exists public.sms_logs (
 id bigint generated by default as identity primary key, key text, value text, text text,
 created_at timestamptz not null default now()
);
alter table public.sms_logs add column if not exists key text;
alter table public.sms_logs add column if not exists value text;
create table if not exists public.app_sessions (
 token_hash text primary key, user_id bigint, is_admin boolean not null default false,
 expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.app_auth_attempts (
 bucket text primary key, attempts integer not null, expires_at timestamptz not null
);
create or replace function public.kino_claim_attempt(bucket_key text)
returns table(allowed boolean) language plpgsql security definer set search_path=public as $$
declare n integer;
begin
 insert into app_auth_attempts(bucket,attempts,expires_at) values(bucket_key,1,now()+interval '15 minutes')
 on conflict(bucket) do update set
 attempts=case when app_auth_attempts.expires_at<=now() then 1 else app_auth_attempts.attempts+1 end,
 expires_at=case when app_auth_attempts.expires_at<=now() then now()+interval '15 minutes' else app_auth_attempts.expires_at end
 returning attempts into n;
 return query select n<=5;
end; $$;
revoke all on function public.kino_claim_attempt(text) from public,anon,authenticated;
grant execute on function public.kino_claim_attempt(text) to service_role;
do $$ declare t text; begin
 foreach t in array array['users','films','pending_payments','contact_messages','sms_logs','app_sessions','app_auth_attempts'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on table public.%I from public, anon, authenticated',t);
 execute format('grant all on table public.%I to service_role',t);
 end loop;
end $$;
grant usage,select on all sequences in schema public to service_role;

-- compatibility-update.sql
-- Add only fields needed by the reviewed app. Does not revoke legacy app access.
-- Run separately from setup.sql on an existing project.
-- Packages have no individual film. Existing film IDs remain unchanged.
alter table public.pending_payments alter column film_id drop not null;
alter table public.sms_logs add column if not exists key text;
alter table public.sms_logs add column if not exists value text;
alter table public.sms_logs add column if not exists text text;
alter table public.films add column if not exists preview_url text default '';
alter table public.pending_payments add column if not exists confirmed_at timestamptz;
alter table public.pending_payments add column if not exists phone text;
create index if not exists kino_payments_owner_status on public.pending_payments(user_id,status);
create index if not exists kino_sessions_expiry on public.app_sessions(expires_at);
notify pgrst, 'reload schema';

-- block-access.sql
alter table public.users add column if not exists access_blocked boolean not null default false;
update public.users set access_blocked=false where access_blocked=true;
-- Compatibility for older server code: cancel only the selected purchase.
create or replace function public.kino_block_access(payment_ref text)
returns setof public.pending_payments
language sql security definer set search_path = public
as $$
  update public.pending_payments set status='revoked'
  where ref_code=payment_ref returning *;
$$;
revoke all on function public.kino_block_access(text) from public, anon, authenticated;
grant execute on function public.kino_block_access(text) to service_role;
notify pgrst, 'reload schema';

-- audit-update.sql
-- Requires setup.sql. Serializes settings writes without deleting old rows.
create or replace function public.kino_save_settings(settings_value text)
returns setof public.sms_logs
language plpgsql security definer set search_path = public as $$
begin
 perform pg_advisory_xact_lock(48129317);
 update public.sms_logs set value=settings_value where key='site_settings';
 if not found then
   insert into public.sms_logs(key,value,text) values('site_settings',settings_value,'settings');
 end if;
 return query select * from public.sms_logs where key='site_settings' order by id desc limit 1;
end; $$;
revoke all on function public.kino_save_settings(text) from public, anon, authenticated;
grant execute on function public.kino_save_settings(text) to service_role;
create index if not exists kino_payments_owner_status_cursor on public.pending_payments(user_id,status,id);
-- A legacy PUBLIC grant must not bypass the role-specific privilege revokes.
do $$ declare t text; begin
 foreach t in array array['users','films','pending_payments','contact_messages','sms_logs','app_sessions','app_auth_attempts'] loop
   execute format('revoke all on table public.%I from public',t);
 end loop;
end $$;
notify pgrst, 'reload schema';
commit;

-- END supabase/review-install.sql


-- ============================================================
-- BEGIN supabase/HTTPS-UPGRADE.sql
-- ============================================================

-- Existing reviewed app: apply poster storage and HTTPS diagnostics.
-- Run in the Supabase SQL Editor. Re-runnable; does not delete images or films.
begin;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('kino-posters','kino-posters',true,200000,array['image/webp'])
on conflict(id) do update set public=true,file_size_limit=200000,allowed_mime_types=array['image/webp'];

-- Restrictive policies also protect this bucket if another application left a
-- permissive "allow all uploads" policy. Other buckets are unaffected.
drop policy if exists kino_posters_no_client_insert on storage.objects;
create policy kino_posters_no_client_insert on storage.objects as restrictive
for insert to anon,authenticated with check(bucket_id <> 'kino-posters');
drop policy if exists kino_posters_no_client_update on storage.objects;
create policy kino_posters_no_client_update on storage.objects as restrictive
for update to anon,authenticated using(bucket_id <> 'kino-posters') with check(bucket_id <> 'kino-posters');
drop policy if exists kino_posters_no_client_delete on storage.objects;
create policy kino_posters_no_client_delete on storage.objects as restrictive
for delete to anon,authenticated using(bucket_id <> 'kino-posters');

-- A migration must not overwrite a poster edited while its upload was running.
create or replace function public.kino_replace_inline_poster(target_id bigint,old_image text,new_image text)
returns table(id bigint) language sql security definer set search_path=public as $$
 update public.films f set img=new_image where f.id=target_id and f.img=old_image
 returning f.id;
$$;
revoke all on function public.kino_replace_inline_poster(bigint,text,text) from public,anon,authenticated;
grant execute on function public.kino_replace_inline_poster(bigint,text,text) to service_role;
notify pgrst,'reload schema';
commit;

begin;
create or replace function public.kino_readiness()
returns table(check_name text,ok boolean)
language sql security definer set search_path=public as $$
 select 'tables_private',count(*)=7 and bool_and(c.relrowsecurity
  and not has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE')
  and not has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE'))
 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'
 and c.relname in ('users','films','pending_payments','contact_messages','sms_logs','app_sessions','app_auth_attempts')
 union all
 select 'poster_bucket',exists(select 1 from storage.buckets where id='kino-posters' and public=true and file_size_limit<=200000 and allowed_mime_types=array['image/webp'])
 union all
 select 'poster_policies',count(*)=3 and bool_and(not polpermissive) from pg_policy where polrelid='storage.objects'::regclass
 and polname in ('kino_posters_no_client_insert','kino_posters_no_client_update','kino_posters_no_client_delete')
 union all
 select 'payment_refs_unique',exists(select 1 from pg_index where indrelid='public.pending_payments'::regclass and indisunique and indisvalid and indexrelid=to_regclass('public.kino_payment_ref_unique'))
 union all
 select 'inline_posters',not exists(select 1 from public.films where img like 'data:image/%')
 union all
 select 'private_functions',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname='public' and p.prosecdef and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE')));
$$;
revoke all on function public.kino_readiness() from public,anon,authenticated;
grant execute on function public.kino_readiness() to service_role;
create index if not exists kino_films_cursor on public.films(id);
notify pgrst,'reload schema';
commit;

-- Updated after inspecting the user's actual legacy payment function bodies.
-- Retire the old log trigger and reference-only payment RPC. Current /api/sms
-- confirms pending_payments directly after its sender, secret, amount and age checks.
-- No function bodies, movie rows, payment rows or log rows are changed/deleted.
-- Missing legacy functions are skipped so this also works on a clean database.
begin;
set local lock_timeout = '5s';
do $$
declare
  signature text;
  target regprocedure;
  legacy_trigger record;
begin
  -- Do not disable an unrelated trigger with the same name, or silently modify
  -- another attachment that was not part of the user's inspected definitions.
  if exists (
    select 1 from pg_trigger t
    where t.tgrelid = to_regclass('public.sms_logs')
      and t.tgname = 'trigger_confirm_payment'
      and (t.tgisinternal or t.tgfoid is distinct from to_regprocedure('public.auto_confirm_payment()')::oid)
  ) then
    raise exception 'Unexpected trigger_confirm_payment definition. Inspect before changing it.';
  end if;
  for legacy_trigger in
    select t.tgname, t.tgrelid, t.tgisinternal
    from pg_trigger t
    where t.tgfoid = to_regprocedure('public.auto_confirm_payment()')
  loop
    if legacy_trigger.tgisinternal
      or legacy_trigger.tgrelid is distinct from to_regclass('public.sms_logs')::oid
      or legacy_trigger.tgname <> 'trigger_confirm_payment' then
      raise exception 'Additional legacy payment trigger attachment requires review.';
    end if;
    execute 'alter table public.sms_logs disable trigger trigger_confirm_payment';
  end loop;

  foreach signature in array array[
    'public.auto_confirm_payment()',
    'public.confirm_payment(text)',
    'public.get_film_cats()',
    'public.update_film_cat(bigint,text)'
  ] loop
    target := to_regprocedure(signature);
    if target is not null then
      execute format('revoke execute on function %s from public, anon, authenticated', target);
      if signature in ('public.auto_confirm_payment()', 'public.confirm_payment(text)') then
        execute format('revoke execute on function %s from service_role', target);
        if has_function_privilege('service_role', target, 'EXECUTE') then
          raise exception 'Legacy payment function still callable by service_role: %', signature;
        end if;
      else
        execute format('grant execute on function %s to service_role', target);
      end if;
      if has_function_privilege('anon', target, 'EXECUTE')
        or has_function_privilege('authenticated', target, 'EXECUTE') then
        raise exception 'Legacy function still publicly callable: %', signature;
      end if;
    end if;
  end loop;
end;
$$;
notify pgrst, 'reload schema';
commit;

-- Verification: anon/authenticated should be false for all four functions.
-- server_execute must be false for the two payment functions, true for the
-- two category functions. auto_confirm_payment's trigger_state must be disabled.
select
  p.oid::regprocedure::text as function_name,
  has_function_privilege('anon', p.oid, 'EXECUTE') as anon_execute,
  has_function_privilege('authenticated', p.oid, 'EXECUTE') as authenticated_execute,
  has_function_privilege('service_role', p.oid, 'EXECUTE') as server_execute,
  coalesce((
    select string_agg(t.tgrelid::regclass::text, ', ' order by t.tgrelid::regclass::text)
    from pg_trigger t
    where t.tgfoid = p.oid and not t.tgisinternal
  ), '-') as trigger_tables,
  coalesce((
    select string_agg(case t.tgenabled when 'D' then 'disabled' else 'ENABLED' end, ', ')
    from pg_trigger t where t.tgfoid = p.oid and not t.tgisinternal
  ), '-') as trigger_state
from pg_proc p
where p.oid::regprocedure = any(array[
  to_regprocedure('public.auto_confirm_payment()'),
  to_regprocedure('public.confirm_payment(text)'),
  to_regprocedure('public.get_film_cats()'),
  to_regprocedure('public.update_film_cat(bigint,text)')
])
order by function_name;

-- END supabase/HTTPS-UPGRADE.sql


-- ============================================================
-- BEGIN supabase/migrations/20260912181211_pin_legacy_function_search_paths.sql
-- ============================================================

-- The inspected legacy bodies use unqualified table names. Public is owned by
-- trusted administrators; anon, authenticated and service_role cannot CREATE
-- there. Put pg_temp last so caller-created tables cannot shadow public tables.
-- Preserve function bodies, owners, ACLs, trigger state and all application data.
set local lock_timeout = '5s';
do $$
declare
  signature text;
  target regprocedure;
begin
  foreach signature in array array[
    'public.auto_confirm_payment()',
    'public.confirm_payment(text)',
    'public.get_film_cats()',
    'public.update_film_cat(bigint,text)'
  ] loop
    target := to_regprocedure(signature);
    if target is not null then
      execute format('alter function %s set search_path = pg_catalog, public, pg_temp', target);
    end if;
  end loop;
end;
$$;

-- END supabase/migrations/20260912181211_pin_legacy_function_search_paths.sql


-- ============================================================
-- BEGIN supabase/migrations/20260915183329_private_support_chat.sql
-- ============================================================

-- Custom HttpOnly app sessions are verified by /api/chat. These tables and
-- invoker RPCs are accessible only to the server's service_role, never public keys.
set local lock_timeout = '5s';
set local statement_timeout = '30s';
alter table public.contact_messages add column if not exists user_id bigint;

create table public.support_threads (
 user_id bigint primary key references public.users(id) on delete cascade,
 updated_at timestamptz not null default now(),
 rate_start timestamptz not null default now(),
 rate_count integer not null default 0
);
create index support_threads_recent on public.support_threads(updated_at desc, user_id desc);
create table public.support_messages (
 id bigint generated always as identity primary key,
 user_id bigint not null references public.support_threads(user_id) on delete cascade,
 sender text not null check (sender in ('user','admin')),
 message text not null default '' check (length(message) <= 2000),
 has_image boolean not null default false,
 client_id uuid not null,
 created_at timestamptz not null default now(),
 read_at timestamptz,
 unique(user_id,sender,client_id),
 check (length(btrim(message)) > 0 or has_image)
);
create index support_messages_thread on public.support_messages(user_id,id desc);
create index support_messages_unread on public.support_messages(sender,user_id,id) where read_at is null;
-- Small, optimized images are private and transactionally coupled to retention.
-- No public URL, unclaimed upload, expired signed URL, or storage cleanup race.
create table public.support_images (
 message_id bigint primary key references public.support_messages(id) on delete cascade,
 data bytea not null check (octet_length(data) between 1 and 350000)
);
alter table public.support_threads enable row level security;
alter table public.support_messages enable row level security;
alter table public.support_images enable row level security;
revoke all on public.support_threads,public.support_messages,public.support_images from public,anon,authenticated;
grant all on public.support_threads,public.support_messages,public.support_images to service_role;
revoke all on sequence public.support_messages_id_seq from public,anon,authenticated;
grant usage,select on sequence public.support_messages_id_seq to service_role;

create function public.kino_chat_send(p_user bigint,p_sender text,p_message text,p_image text,p_client uuid)
returns table(id bigint,user_id bigint,sender text,message text,has_image boolean,client_id uuid,created_at timestamptz,read_at timestamptz)
language plpgsql security invoker set search_path = '' as $$
declare t public.support_threads; saved public.support_messages; image_bytes bytea;
begin
 if p_user is null or p_sender is null or p_sender not in ('admin','user') or p_client is null
    or p_message is null or length(p_message)>2000 or (length(btrim(p_message))=0 and p_image is null)
 then raise exception 'Invalid message' using errcode='22023'; end if;
 if p_image is not null then
   if length(p_image)>466668 then raise exception 'Image too large' using errcode='22023'; end if;
   image_bytes := decode(p_image,'base64');
   if octet_length(image_bytes) not between 1 and 350000 then raise exception 'Invalid image' using errcode='22023'; end if;
 end if;
 insert into public.support_threads(user_id) values(p_user) on conflict do nothing;
 -- Serialize writers before assigning IDs and trimming. Concurrent sends cannot
 -- exceed 100 messages or delete messages belonging to another conversation.
 select * into t from public.support_threads s where s.user_id=p_user for update;
 select * into saved from public.support_messages m where m.user_id=p_user and m.sender=p_sender and m.client_id=p_client;
 if found then
   return query select m.id,m.user_id,m.sender,m.message,m.has_image,m.client_id,m.created_at,m.read_at from public.support_messages m where m.id=saved.id;
   return;
 end if;
 if t.rate_start > now()-interval '1 minute' and t.rate_count >= 60 then
   raise exception 'Message rate exceeded' using errcode='P0429';
 end if;
 update public.support_threads s set updated_at=clock_timestamp(),
   rate_count=case when t.rate_start <= now()-interval '1 minute' then 1 else t.rate_count+1 end,
   rate_start=case when t.rate_start <= now()-interval '1 minute' then now() else t.rate_start end
 where s.user_id=p_user;
 insert into public.support_messages(user_id,sender,message,has_image,client_id)
 values(p_user,p_sender,btrim(p_message),p_image is not null,p_client) returning * into saved;
 if image_bytes is not null then insert into public.support_images(message_id,data) values(saved.id,image_bytes); end if;
 delete from public.support_messages m where m.user_id=p_user and m.id in
   (select old.id from public.support_messages old where old.user_id=p_user order by old.id desc offset 100);
 return query select m.id,m.user_id,m.sender,m.message,m.has_image,m.client_id,m.created_at,m.read_at from public.support_messages m where m.id=saved.id;
end $$;

create function public.kino_chat_inbox(p_search text default '',p_offset integer default 0)
returns table(user_id bigint,phone text,label text,message text,has_image boolean,sender text,updated_at timestamptz,unread bigint)
language sql stable security invoker set search_path = '' as $$
 select t.user_id,u.phone,u.user_id,m.message,m.has_image,m.sender,t.updated_at,
 (select count(*) from public.support_messages n where n.user_id=t.user_id and n.sender='user' and n.read_at is null)
 from public.support_threads t join public.users u on u.id=t.user_id
 join lateral (select s.message,s.has_image,s.sender from public.support_messages s where s.user_id=t.user_id order by s.id desc limit 1) m on true
 where p_search='' or position(p_search in u.phone)>0 or position(p_search in coalesce(u.user_id,''))>0
 order by t.updated_at desc,t.user_id desc limit 51 offset greatest(0,least(p_offset,1000000));
$$;

create function public.kino_chat_unread(p_user bigint,p_admin boolean)
returns table(unread bigint) language sql stable security invoker set search_path = '' as $$
 select count(*) from public.support_messages m where m.read_at is null
 and m.sender=case when p_admin then 'user' else 'admin' end and (p_admin or m.user_id=p_user);
$$;
revoke all on function public.kino_chat_send(bigint,text,text,text,uuid),public.kino_chat_inbox(text,integer),public.kino_chat_unread(bigint,boolean) from public,anon,authenticated;
grant execute on function public.kino_chat_send(bigint,text,text,text,uuid),public.kino_chat_inbox(text,integer),public.kino_chat_unread(bigint,boolean) to service_role;

-- Preserve the latest 100 legacy messages/replies with an explicit valid owner.
-- Original requests and announcements remain untouched for audit/recovery.
insert into public.support_threads(user_id,updated_at)
 select u.id,coalesce(max(c.created_at),now()) from public.contact_messages c join public.users u on u.id=c.user_id
 where c.is_announcement is not true and (length(btrim(coalesce(c.message,'')))>0 or length(btrim(coalesce(c.reply,'')))>0)
 group by u.id on conflict do nothing;
with legacy as (
 select c.user_id,c.id legacy_id,'user'::text sender,left(c.message,2000) message,
   md5('legacy-user-'||c.id)::uuid client_id,coalesce(c.created_at,now()) created_at,
   case when c.read then coalesce(c.created_at,now()) end read_at,0 part
 from public.contact_messages c join public.users u on u.id=c.user_id
 where c.is_announcement is not true and length(btrim(coalesce(c.message,'')))>0
 union all
 select c.user_id,c.id,'admin',left(c.reply,2000),md5('legacy-admin-'||c.id)::uuid,
   coalesce(c.created_at,now()),case when (to_jsonb(c)->>'user_read')::boolean then coalesce(c.created_at,now()) end,1
 from public.contact_messages c join public.users u on u.id=c.user_id
 where c.is_announcement is not true and length(btrim(coalesce(c.reply,'')))>0
), ranked as (
 select *,row_number() over(partition by user_id order by created_at desc,legacy_id desc,part desc) rn from legacy
)
insert into public.support_messages(user_id,sender,message,client_id,created_at,read_at)
 select user_id,sender,message,client_id,created_at,read_at from ranked where rn<=100 order by created_at,legacy_id,part;
notify pgrst,'reload schema';

-- END supabase/migrations/20260915183329_private_support_chat.sql


-- ============================================================
-- BEGIN supabase/migrations/20260915200520_chat_access_actions.sql
-- ============================================================

set local lock_timeout = '5s';
set local statement_timeout = '30s';
alter table public.support_threads
 add column user_seen_at timestamptz, add column admin_seen_at timestamptz,
 add column user_typing_at timestamptz, add column admin_typing_at timestamptz;
alter table public.support_messages add column grant_payment_id bigint references public.pending_payments(id) on delete set null;

-- Presence contains timestamps only, never the draft being typed.
create function public.kino_chat_activity(p_user bigint,p_admin boolean,p_active boolean,p_typing boolean)
returns table(ok boolean) language plpgsql security invoker set search_path = '' as $$
begin
 if p_user is null or p_admin is null or p_active is null or p_typing is null then raise exception 'Invalid activity' using errcode='22023'; end if;
 insert into public.support_threads(user_id) values(p_user) on conflict do nothing;
 if p_admin then
  update public.support_threads set admin_seen_at=case when p_active then clock_timestamp() end,
   admin_typing_at=case when p_active and p_typing then clock_timestamp() end where user_id=p_user;
 else
  update public.support_threads set user_seen_at=case when p_active then clock_timestamp() end,
   user_typing_at=case when p_active and p_typing then clock_timestamp() end where user_id=p_user;
 end if;
 return query select true;
end $$;

create function public.kino_chat_view(p_user bigint,p_admin boolean)
returns table(messages jsonb,peer_online boolean,peer_typing boolean)
language sql stable security invoker set search_path = '' as $$
 select coalesce((select jsonb_agg(to_jsonb(m) order by m.id) from
  (select id,sender,message,has_image,client_id,created_at,read_at,grant_payment_id
   from public.support_messages where user_id=p_user order by id desc limit 100) m),'[]'::jsonb),
 coalesce((select (case when p_admin then user_seen_at else admin_seen_at end)>now()-interval '35 seconds' from public.support_threads where user_id=p_user),false),
 coalesce((select (case when p_admin then user_typing_at else admin_typing_at end)>now()-interval '6 seconds' from public.support_threads where user_id=p_user),false);
$$;

-- Delete only the messages included in the admin's confirmation. New arrivals
-- survive; cascades delete photos. Payment/grant records are never deleted.
create function public.kino_chat_clear(p_user bigint,p_through bigint)
returns table(deleted bigint) language plpgsql security invoker set search_path = '' as $$
declare n bigint;
begin
 if p_user is null or p_through is null or p_through<1 then raise exception 'Invalid clear' using errcode='22023'; end if;
 perform 1 from public.support_threads where user_id=p_user for update;
 delete from public.support_messages where user_id=p_user and id<=p_through;
 get diagnostics n=row_count;
 return query select n;
end $$;

-- One atomic grant + chat receipt. Durable payment ref makes lost-response
-- retries safe even after the chat was cleared or its 100-message retention.
create function public.kino_chat_grant(p_user bigint,p_plan text,p_film bigint,p_request uuid)
returns table(payment_id bigint,plan text,film_id bigint,expires_at timestamptz)
language plpgsql security invoker set search_path = '' as $$
declare owner public.users; saved public.pending_payments; film_title text; label text; days integer; receipt bigint;
begin
 if p_user is null or p_request is null or p_plan is null or p_plan not in
  ('single','3day','all_1month','erotic_3day','gadaad_3day','hyatad_3day','erotic_1month','gadaad_1month','hyatad_1month')
 then raise exception 'Invalid grant' using errcode='22023'; end if;
 if (p_plan='single' and p_film is null) or (p_plan<>'single' and p_film is not null) then raise exception 'Invalid film' using errcode='22023'; end if;
 select * into owner from public.users where id=p_user for update;
 if not found then raise exception 'Unknown user' using errcode='P0404'; end if;
 days := case when p_plan in ('single','3day') or right(p_plan,5)='_3day' then 3 else 30 end;
 select * into saved from public.pending_payments where ref_code='chat-'||p_request::text;
 if found then
  if saved.user_id<>p_user or saved.plan<>p_plan or saved.film_id is distinct from p_film or saved.status<>'confirmed' then raise exception 'Grant changed' using errcode='P0409'; end if;
 else
  if p_plan='single' then
   select title into film_title from public.films where id=p_film;
   if not found then raise exception 'Unknown film' using errcode='P0404'; end if;
   label := '«'||left(coalesce(film_title,'Кино'),200)||'» кино · 3 хоног';
  else
   label := case split_part(p_plan,'_',1) when 'erotic' then 'Эротик' when 'gadaad' then 'Гадаад' when 'hyatad' then 'Хятад' else 'Бүх кино' end || ' · ' || days || ' хоног';
  end if;
  insert into public.pending_payments(ref_code,user_id,phone,film_id,plan,amount,status,confirmed_at)
   values('chat-'||p_request::text,p_user,owner.phone,p_film,p_plan,0,'confirmed',clock_timestamp()) returning * into saved;
  select id into receipt from public.kino_chat_send(p_user,'admin',
   '✅ Таны '||label||' үзэх эрхийг админ нээлээ. Хүчинтэй хугацаа: '||
   to_char((saved.confirmed_at+make_interval(days=>days)) at time zone 'Asia/Ulaanbaatar','YYYY-MM-DD HH24:MI')||' (Улаанбаатар).',null,p_request);
  update public.support_messages set grant_payment_id=saved.id where id=receipt;
 end if;
 return query select saved.id,p_plan,p_film,saved.confirmed_at+make_interval(days=>days);
end $$;

revoke all on function public.kino_chat_activity(bigint,boolean,boolean,boolean),public.kino_chat_view(bigint,boolean),public.kino_chat_clear(bigint,bigint),public.kino_chat_grant(bigint,text,bigint,uuid) from public,anon,authenticated;
grant execute on function public.kino_chat_activity(bigint,boolean,boolean,boolean),public.kino_chat_view(bigint,boolean),public.kino_chat_clear(bigint,bigint),public.kino_chat_grant(bigint,text,bigint,uuid) to service_role;
notify pgrst,'reload schema';

-- END supabase/migrations/20260915200520_chat_access_actions.sql


-- ============================================================
-- BEGIN supabase/migrations/20260916032117_site_appearance.sql
-- ============================================================

-- One public theme, written only through the server's authenticated admin route.
-- Kept separate from Messenger settings and SMS/payment records.
create table if not exists public.site_appearance (
  id integer primary key default 1 check (id = 1),
  layout integer not null default 1 check (layout between 1 and 4),
  tone integer not null default 25 check (tone between 0 and 100),
  revision integer not null default 0 check (revision >= 0)
);
alter table public.site_appearance enable row level security;
revoke all on public.site_appearance from public, anon, authenticated, service_role;
grant select on public.site_appearance to service_role;
grant update (layout,tone,revision) on public.site_appearance to service_role;
drop policy if exists site_appearance_server on public.site_appearance;
create policy site_appearance_server on public.site_appearance to service_role using (true) with check (true);
insert into public.site_appearance(id,layout,tone,revision) values (1,1,25,0) on conflict (id) do nothing;
comment on table public.site_appearance is 'Singleton site appearance. The Next.js API authenticates admin writes and validates layout/tone. Browser roles have no direct access.';
notify pgrst, 'reload schema';

-- END supabase/migrations/20260916032117_site_appearance.sql


-- ============================================================
-- BEGIN supabase/migrations/20260917071000_guest_device_access.sql
-- ============================================================

set local lock_timeout = '5s';
set local statement_timeout = '30s';

alter table public.users add column if not exists is_guest boolean not null default false;
create index if not exists kino_users_guest_created on public.users(created_at) where is_guest;

-- Keep the existing inbox contract, but give anonymous devices a safe, readable label.
create or replace function public.kino_chat_inbox(p_search text default '',p_offset integer default 0)
returns table(user_id bigint,phone text,label text,message text,has_image boolean,sender text,updated_at timestamptz,unread bigint)
language sql stable security invoker set search_path = '' as $$
 select t.user_id,
   case when u.is_guest then 'Төхөөрөмж '||coalesce(u.user_id,'#'||u.id::text) else u.phone end,
   u.user_id,m.message,m.has_image,m.sender,t.updated_at,
   (select count(*) from public.support_messages n where n.user_id=t.user_id and n.sender='user' and n.read_at is null)
 from public.support_threads t join public.users u on u.id=t.user_id
 join lateral (select s.message,s.has_image,s.sender from public.support_messages s where s.user_id=t.user_id order by s.id desc limit 1) m on true
 where p_search='' or position(lower(p_search) in lower(coalesce(u.phone,'')))>0 or position(lower(p_search) in lower(coalesce(u.user_id,'')))>0
 order by t.updated_at desc,t.user_id desc limit 51 offset greatest(0,least(p_offset,1000000));
$$;
revoke all on function public.kino_chat_inbox(text,integer) from public,anon,authenticated;
grant execute on function public.kino_chat_inbox(text,integer) to service_role;
notify pgrst,'reload schema';

-- END supabase/migrations/20260917071000_guest_device_access.sql
