-- Kino site review migration. Back up the database first. All changes are atomic.
begin;

-- setup.sql
-- Run once in Supabase SQL Editor. No existing film/order/user rows are deleted.
-- Back up the database first. This intentionally closes direct browser REST access.
create table if not exists public.users (
 id bigint generated by default as identity primary key, phone text unique not null,
 pin text not null, user_id text unique not null, failed_attempts integer default 0,
 locked_until timestamptz, created_at timestamptz not null default now()
);
-- Existing 4-character PIN columns must accommodate scrypt hashes.
alter table public.users alter column pin type text;
alter table public.users add column if not exists failed_attempts integer default 0;
alter table public.users add column if not exists locked_until timestamptz;
alter table public.users add column if not exists created_at timestamptz not null default now();
create unique index if not exists kino_users_phone_unique on public.users(phone);
create table if not exists public.films (
 id bigint generated by default as identity primary key, title text not null,
 views integer default 0, op integer default 0, price integer default 0,
 badge text default 'Хэлтэй', free boolean default false, locked boolean default true,
 url text default '', img text default '', bg text default '#1a0820',
 preview_url text default '', created_at timestamptz not null default now()
);
alter table public.films add column if not exists preview_url text default '';
-- Copy only already-designated trailers into their public column.
update public.films set preview_url=split_part(url,'|||',2)
 where coalesce(preview_url,'')='' and position('|||' in coalesce(url,''))>0;
create table if not exists public.pending_payments (
 id bigint generated by default as identity primary key, ref_code text not null,
 user_id bigint, film_id bigint, phone text, plan text not null default 'single',
 amount numeric not null, status text not null default 'pending',
 confirmed_at timestamptz, created_at timestamptz not null default now()
);
alter table public.pending_payments alter column film_id drop not null;
alter table public.pending_payments add column if not exists confirmed_at timestamptz;
alter table public.pending_payments add column if not exists phone text;
-- If duplicate refs exist, this fails and rolls back; inspect them manually, do not delete blindly.
create unique index if not exists kino_payment_ref_unique on public.pending_payments(ref_code);
create table if not exists public.contact_messages (
 id bigint generated by default as identity primary key, phone text, message text,
 reply text, read boolean default false, is_announcement boolean default false,
 announcement_image text, created_at timestamptz not null default now()
);
create table if not exists public.sms_logs (
 id bigint generated by default as identity primary key, key text, value text, text text,
 created_at timestamptz not null default now()
);
alter table public.sms_logs add column if not exists key text;
alter table public.sms_logs add column if not exists value text;
create table if not exists public.app_sessions (
 token_hash text primary key, user_id bigint, is_admin boolean not null default false,
 expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.app_auth_attempts (
 bucket text primary key, attempts integer not null, expires_at timestamptz not null
);
create or replace function public.kino_claim_attempt(bucket_key text)
returns table(allowed boolean) language plpgsql security definer set search_path=public as $$
declare n integer;
begin
 insert into app_auth_attempts(bucket,attempts,expires_at) values(bucket_key,1,now()+interval '15 minutes')
 on conflict(bucket) do update set
 attempts=case when app_auth_attempts.expires_at<=now() then 1 else app_auth_attempts.attempts+1 end,
 expires_at=case when app_auth_attempts.expires_at<=now() then now()+interval '15 minutes' else app_auth_attempts.expires_at end
 returning attempts into n;
 return query select n<=5;
end; $$;
revoke all on function public.kino_claim_attempt(text) from public,anon,authenticated;
grant execute on function public.kino_claim_attempt(text) to service_role;
do $$ declare t text; begin
 foreach t in array array['users','films','pending_payments','contact_messages','sms_logs','app_sessions','app_auth_attempts'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on table public.%I from public, anon, authenticated',t);
 execute format('grant all on table public.%I to service_role',t);
 end loop;
end $$;
grant usage,select on all sequences in schema public to service_role;

-- compatibility-update.sql
-- Add only fields needed by the reviewed app. Does not revoke legacy app access.
-- Run separately from setup.sql on an existing project.
-- Packages have no individual film. Existing film IDs remain unchanged.
alter table public.pending_payments alter column film_id drop not null;
alter table public.sms_logs add column if not exists key text;
alter table public.sms_logs add column if not exists value text;
alter table public.sms_logs add column if not exists text text;
alter table public.films add column if not exists preview_url text default '';
alter table public.pending_payments add column if not exists confirmed_at timestamptz;
alter table public.pending_payments add column if not exists phone text;
create index if not exists kino_payments_owner_status on public.pending_payments(user_id,status);
create index if not exists kino_sessions_expiry on public.app_sessions(expires_at);
notify pgrst, 'reload schema';

-- block-access.sql
alter table public.users add column if not exists access_blocked boolean not null default false;
update public.users set access_blocked=false where access_blocked=true;
-- Compatibility for older server code: cancel only the selected purchase.
create or replace function public.kino_block_access(payment_ref text)
returns setof public.pending_payments
language sql security definer set search_path = public
as $$
  update public.pending_payments set status='revoked'
  where ref_code=payment_ref returning *;
$$;
revoke all on function public.kino_block_access(text) from public, anon, authenticated;
grant execute on function public.kino_block_access(text) to service_role;
notify pgrst, 'reload schema';

-- audit-update.sql
-- Requires setup.sql. Serializes settings writes without deleting old rows.
create or replace function public.kino_save_settings(settings_value text)
returns setof public.sms_logs
language plpgsql security definer set search_path = public as $$
begin
 perform pg_advisory_xact_lock(48129317);
 update public.sms_logs set value=settings_value where key='site_settings';
 if not found then
   insert into public.sms_logs(key,value,text) values('site_settings',settings_value,'settings');
 end if;
 return query select * from public.sms_logs where key='site_settings' order by id desc limit 1;
end; $$;
revoke all on function public.kino_save_settings(text) from public, anon, authenticated;
grant execute on function public.kino_save_settings(text) to service_role;
create index if not exists kino_payments_owner_status_cursor on public.pending_payments(user_id,status,id);
-- A legacy PUBLIC grant must not bypass the role-specific privilege revokes.
do $$ declare t text; begin
 foreach t in array array['users','films','pending_payments','contact_messages','sms_logs','app_sessions','app_auth_attempts'] loop
   execute format('revoke all on table public.%I from public',t);
 end loop;
end $$;
notify pgrst, 'reload schema';
commit;
