-- Run once in Supabase SQL Editor. No existing film/order/user rows are deleted.
-- Back up the database first. This intentionally closes direct browser REST access.
begin;
create table if not exists public.users (
 id bigint generated by default as identity primary key, phone text unique not null,
 pin text not null, user_id text unique not null, failed_attempts integer default 0,
 locked_until timestamptz, created_at timestamptz not null default now()
);
-- Existing 4-character PIN columns must accommodate scrypt hashes.
alter table public.users alter column pin type text;
alter table public.users add column if not exists failed_attempts integer default 0;
alter table public.users add column if not exists locked_until timestamptz;
alter table public.users add column if not exists created_at timestamptz not null default now();
create unique index if not exists kino_users_phone_unique on public.users(phone);
create table if not exists public.films (
 id bigint generated by default as identity primary key, title text not null,
 views integer default 0, op integer default 0, price integer default 0,
 badge text default 'Хэлтэй', free boolean default false, locked boolean default true,
 url text default '', img text default '', bg text default '#1a0820',
 preview_url text default '', created_at timestamptz not null default now()
);
alter table public.films add column if not exists preview_url text default '';
-- Copy only already-designated trailers into their public column.
update public.films set preview_url=split_part(url,'|||',2)
 where coalesce(preview_url,'')='' and position('|||' in coalesce(url,''))>0;
create table if not exists public.pending_payments (
 id bigint generated by default as identity primary key, ref_code text not null,
 user_id bigint, film_id bigint, phone text, plan text not null default 'single',
 amount numeric not null, status text not null default 'pending',
 confirmed_at timestamptz, created_at timestamptz not null default now()
);
alter table public.pending_payments alter column film_id drop not null;
alter table public.pending_payments add column if not exists confirmed_at timestamptz;
alter table public.pending_payments add column if not exists phone text;
-- If duplicate refs exist, this fails and rolls back; inspect them manually, do not delete blindly.
create unique index if not exists kino_payment_ref_unique on public.pending_payments(ref_code);
create table if not exists public.contact_messages (
 id bigint generated by default as identity primary key, phone text, message text,
 reply text, read boolean default false, is_announcement boolean default false,
 announcement_image text, created_at timestamptz not null default now()
);
create table if not exists public.sms_logs (
 id bigint generated by default as identity primary key, key text, value text, text text,
 created_at timestamptz not null default now()
);
alter table public.sms_logs add column if not exists key text;
alter table public.sms_logs add column if not exists value text;
create table if not exists public.app_sessions (
 token_hash text primary key, user_id bigint, is_admin boolean not null default false,
 expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.app_auth_attempts (
 bucket text primary key, attempts integer not null, expires_at timestamptz not null
);
create or replace function public.kino_claim_attempt(bucket_key text)
returns table(allowed boolean) language plpgsql security definer set search_path=public as $$
declare n integer;
begin
 insert into app_auth_attempts(bucket,attempts,expires_at) values(bucket_key,1,now()+interval '15 minutes')
 on conflict(bucket) do update set
 attempts=case when app_auth_attempts.expires_at<=now() then 1 else app_auth_attempts.attempts+1 end,
 expires_at=case when app_auth_attempts.expires_at<=now() then now()+interval '15 minutes' else app_auth_attempts.expires_at end
 returning attempts into n;
 return query select n<=5;
end; $$;
revoke all on function public.kino_claim_attempt(text) from public,anon,authenticated;
grant execute on function public.kino_claim_attempt(text) to service_role;
do $$ declare t text; begin
 foreach t in array array['users','films','pending_payments','contact_messages','sms_logs','app_sessions','app_auth_attempts'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on table public.%I from public, anon, authenticated',t);
 execute format('grant all on table public.%I to service_role',t);
 end loop;
end $$;
grant usage,select on all sequences in schema public to service_role;
commit;
