-- Multi-site foundation. This migration is intentionally additive so the existing TAZA
-- production code continues to work until the multi-site branch is fully verified.

create table if not exists public.sites (
  id text primary key,
  name text not null,
  path text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint sites_id_check check (id in ('taza','kino-drama','kinochid','fire'))
);

insert into public.sites(id,name,path)
values
  ('taza','ТАЗА САЙТ','/'),
  ('kino-drama','КИНО ДРАМА','/kino-drama'),
  ('kinochid','КИНОЧИД','/kinochid'),
  ('fire','FIRE','/fire')
on conflict(id) do update set name=excluded.name,path=excluded.path;

alter table public.films add column if not exists site_id text not null default 'taza';
alter table public.pending_payments add column if not exists site_id text not null default 'taza';
alter table public.wallet_ledger add column if not exists site_id text not null default 'taza';
alter table public.site_events add column if not exists site_id text not null default 'taza';
alter table public.app_sessions add column if not exists admin_site_id text;
alter table public.push_subscriptions add column if not exists site_id text not null default 'taza';
alter table public.contact_messages add column if not exists site_id text not null default 'taza';
alter table public.site_appearance add column if not exists site_id text not null default 'taza';

do $$
begin
  if not exists(select 1 from pg_constraint where conname='films_site_id_fkey') then
    alter table public.films add constraint films_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='pending_payments_site_id_fkey') then
    alter table public.pending_payments add constraint pending_payments_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='wallet_ledger_site_id_fkey') then
    alter table public.wallet_ledger add constraint wallet_ledger_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='site_events_site_id_fkey') then
    alter table public.site_events add constraint site_events_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='app_sessions_admin_site_id_fkey') then
    alter table public.app_sessions add constraint app_sessions_admin_site_id_fkey foreign key(admin_site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='push_subscriptions_site_id_fkey') then
    alter table public.push_subscriptions add constraint push_subscriptions_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='contact_messages_site_id_fkey') then
    alter table public.contact_messages add constraint contact_messages_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='site_appearance_site_id_fkey') then
    alter table public.site_appearance add constraint site_appearance_site_id_fkey foreign key(site_id) references public.sites(id);
  end if;
end $$;

create index if not exists films_site_id_id_idx on public.films(site_id,id);
create index if not exists pending_payments_site_user_idx on public.pending_payments(site_id,user_id,id);
create index if not exists pending_payments_site_ref_idx on public.pending_payments(site_id,ref_code);
create index if not exists wallet_ledger_site_user_idx on public.wallet_ledger(site_id,user_id,id);
create index if not exists site_events_site_created_idx on public.site_events(site_id,created_at desc);
create index if not exists push_subscriptions_site_user_idx on public.push_subscriptions(site_id,user_id);
create index if not exists contact_messages_site_created_idx on public.contact_messages(site_id,created_at desc);
create unique index if not exists site_appearance_site_unique on public.site_appearance(site_id);

create table if not exists public.site_admins (
  id bigint generated by default as identity primary key,
  site_id text not null references public.sites(id) on delete cascade,
  label text not null,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_admins_label_len check (char_length(label) between 1 and 80),
  constraint site_admins_password_hash_len check (char_length(password_hash) between 32 and 300)
);
create index if not exists site_admins_site_active_idx on public.site_admins(site_id,active);

alter table public.sites enable row level security;
alter table public.site_admins enable row level security;
revoke all on public.sites from public,anon,authenticated;
revoke all on public.site_admins from public,anon,authenticated;
grant select,insert,update,delete on public.sites to service_role;
grant select,insert,update,delete on public.site_admins to service_role;
grant usage,select on sequence public.site_admins_id_seq to service_role;

-- New site appearance rows can be created later after the multi-site API is active.
-- Existing row(s) remain site_id='taza', preserving current production behavior.

notify pgrst,'reload schema';
